### ISSUE TITLE
[Feature Request] 添加物品特殊功能的 tooltip

### ISSUE THREAD

**Issue by EvanHsieh0415** [Gu-meng/SkyblockExplore#2]
例如 `碎骨劍` 有個攻擊時有機率傷害自己的設定，可以在 tooltip 中說明。

**Comment by Gu-meng** [comment]
加的一点点“特色”，玩家在游玩过程中发现感觉会更有意思

**Comment by EvanHsieh0415** [comment]
有些玩家沒辦法將特色連結在一起，建議明顯提示或是在 JEI Info 中提醒會比較好

**Comment by Gu-meng** [comment]
想了想，这种特色可以通过”成就“的形式来表现

**Comment by Gu-meng** [comment]
https://github.com/Gu-meng/SkyblockExplore/commit/eaf32670f3318989f7dd2f3e896734454866ec17
